local protocol = require("jusi.protocol")

local function read_json(path)
  local file = assert(io.open(path, "r"))
  local content = file:read("*a")
  file:close()
  return vim.json.decode(content)
end

local scenario = read_json("protocol/fixtures/v1/scenarios/walking-skeleton.json")
for _, command in ipairs(scenario.commands) do
  local ok, err = protocol.validate_command(command, command.kind)
  assert(ok, err)
end
local restart_scenario = read_json("protocol/fixtures/v1/scenarios/restart-notebook.json")
local restart_ok, restart_error = protocol.validate_command(restart_scenario.command, "restart_notebook")
assert(restart_ok, restart_error)

local close_client = read_json("protocol/fixtures/v1/valid/close-client.json")
local close_ok, close_error = protocol.validate_command(close_client, "close_client")
assert(close_ok, close_error)

local invalid = read_json("protocol/fixtures/v1/invalid/command-missing-trace-id.json")
local ok = protocol.validate_command(invalid, invalid.kind)
assert(not ok, "invalid fixture must be rejected")

local event = read_json("protocol/fixtures/v1/valid/execution-output.json")
local event_ok, event_err = protocol.validate_event(event)
assert(event_ok, event_err)
assert(event.payload.data == "\27[31mred\27[0m", "ANSI output must remain unchanged")

local invalid_event = read_json("protocol/fixtures/v1/invalid/event-missing-sequence.json")
local invalid_event_ok = protocol.validate_event(invalid_event)
assert(not invalid_event_ok, "invalid event fixture must be rejected")
local event_scenario = read_json("protocol/fixtures/v1/scenarios/event-payloads.json")
for _, fixture_event in ipairs(event_scenario.events) do
  local fixture_ok, fixture_error = protocol.validate_event(fixture_event)
  assert(fixture_ok, fixture_error)
end
local malformed_output = read_json("protocol/fixtures/v1/invalid/event-output-missing-data.json")
local malformed_output_ok = protocol.validate_event(malformed_output)
assert(not malformed_output_ok, "malformed output payload must be rejected")
local invalid_client = read_json("protocol/fixtures/v1/invalid/client-created-missing-worker.json")
local invalid_client_ok = protocol.validate_event(invalid_client)
assert(not invalid_client_ok, "client identity must include its exact worker")
local surface_created = read_json("protocol/fixtures/v1/valid/surface-created.json")
local surface_created_ok, surface_created_error = protocol.validate_event(surface_created)
assert(surface_created_ok, surface_created_error)
local surface_closed = read_json("protocol/fixtures/v1/valid/surface-closed.json")
local surface_closed_ok, surface_closed_error = protocol.validate_event(surface_closed)
assert(surface_closed_ok, surface_closed_error)
local invalid_surface = read_json("protocol/fixtures/v1/invalid/surface-created-missing-transport.json")
local invalid_surface_ok = protocol.validate_event(invalid_surface)
assert(not invalid_surface_ok, "surface transport descriptor is required")

local health = read_json("protocol/fixtures/v1/valid/health-response.json")
local health_ok, health_error = protocol.validate_health_response(health)
assert(health_ok, health_error)
local invalid_health = read_json("protocol/fixtures/v1/invalid/health-invalid-window.json")
local invalid_health_ok = protocol.validate_health_response(invalid_health)
assert(not invalid_health_ok, "invalid health fixture must be rejected")
local mismatched_health = read_json("protocol/fixtures/v1/invalid/health-runtime-mismatch.json")
local mismatched_health_ok = protocol.validate_health_response(mismatched_health)
assert(not mismatched_health_ok, "runtime/kernel ownership mismatch must be rejected")
local missing_surfaces_health = read_json("protocol/fixtures/v1/invalid/health-missing-surfaces.json")
local missing_surfaces_health_ok = protocol.validate_health_response(missing_surfaces_health)
assert(not missing_surfaces_health_ok, "authoritative health must include surfaces")

local plugin_catalog = read_json("protocol/fixtures/v1/valid/plugin-catalog.json")
local catalog_ok, catalog_error = protocol.validate_plugin_catalog(plugin_catalog)
assert(catalog_ok, catalog_error)
local invalid_catalog = read_json("protocol/fixtures/v1/invalid/plugin-catalog-duplicate-id.json")
local invalid_catalog_ok = protocol.validate_plugin_catalog(invalid_catalog)
assert(not invalid_catalog_ok, "duplicate plugin identities must be rejected")
local conflicting_catalog = read_json("protocol/fixtures/v1/invalid/plugin-catalog-conflicting-family.json")
local conflicting_catalog_ok = protocol.validate_plugin_catalog(conflicting_catalog)
assert(not conflicting_catalog_ok, "incompatible shared family claims must be rejected")
local short_identity_catalog = read_json("protocol/fixtures/v1/invalid/plugin-catalog-short-identity.json")
local short_identity_catalog_ok = protocol.validate_plugin_catalog(short_identity_catalog)
assert(not short_identity_catalog_ok, "catalog schema string bounds must be enforced")
local duplicate_kernel_module = read_json("protocol/fixtures/v1/invalid/plugin-catalog-duplicate-kernel-module.json")
local duplicate_kernel_module_ok = protocol.validate_plugin_catalog(duplicate_kernel_module)
assert(not duplicate_kernel_module_ok, "one kernel module cannot belong to multiple exact plugins")

local worker_request = read_json("protocol/fixtures/v1/valid/plugin-worker-request.json")
local worker_request_ok, worker_request_error = protocol.validate_plugin_worker_message(worker_request)
assert(worker_request_ok, worker_request_error)
local worker_result = read_json("protocol/fixtures/v1/valid/plugin-worker-result.json")
local worker_result_ok, worker_result_error = protocol.validate_plugin_worker_message(worker_result)
assert(worker_result_ok, worker_result_error)
local terminal_request_result = read_json("protocol/fixtures/v1/valid/plugin-worker-terminal-surface-request.json")
local terminal_request_ok, terminal_request_error = protocol.validate_plugin_worker_message(terminal_request_result)
assert(terminal_request_ok, terminal_request_error)
local invalid_terminal_request = read_json("protocol/fixtures/v1/invalid/plugin-worker-terminal-surface-missing-resize.json")
local invalid_terminal_request_ok = protocol.validate_plugin_worker_message(invalid_terminal_request)
assert(not invalid_terminal_request_ok, "terminal surface requests require resize capability")
local missing_core_requests = read_json("protocol/fixtures/v1/invalid/plugin-worker-result-missing-core-requests.json")
local missing_core_requests_ok = protocol.validate_plugin_worker_message(missing_core_requests)
assert(not missing_core_requests_ok, "worker results require an explicit core_requests array")
local invalid_worker = read_json("protocol/fixtures/v1/invalid/plugin-worker-identity-missing.json")
local invalid_worker_ok = protocol.validate_plugin_worker_message(invalid_worker)
assert(not invalid_worker_ok, "worker identity is required")

local adapters_ready = read_json("protocol/fixtures/v1/valid/plugin-adapters-ready.json")
local adapters_ready_ok, adapters_ready_error = protocol.validate_plugin_kernel_message(adapters_ready)
assert(adapters_ready_ok, adapters_ready_error)
local plugin_handoff = read_json("protocol/fixtures/v1/valid/plugin-handoff.json")
local plugin_handoff_ok, plugin_handoff_error = protocol.validate_plugin_kernel_message(plugin_handoff)
assert(plugin_handoff_ok, plugin_handoff_error)
local invalid_handoff = read_json("protocol/fixtures/v1/invalid/plugin-handoff-missing-provider.json")
local invalid_handoff_ok = protocol.validate_plugin_kernel_message(invalid_handoff)
assert(not invalid_handoff_ok, "plugin handoff provider identity is required")

local specs = vim.fn.glob("tests/frontend/*_spec.lua", false, true)
table.sort(specs)
for _, path in ipairs(specs) do
  dofile(path).run()
end
dofile("tests/frontend/benchmark.lua").run()

print("Lua frontend tests passed")
